FROM mcr.microsoft.com/windows/servercore:latest
LABEL maintainer="SystemClone"

# Install Chocolatey package manager
RUN powershell -Command Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Add Chocolatey to PATH
RUN setx /M PATH "%PATH%;C:\ProgramData\chocolatey\bin"

ENV ALLUSERSPROFILE="C:\ProgramData"
ENV APPDATA="C:\Users\Sreyas P Pradeep\AppData\Roaming"
ENV CHROME_CRASHPAD_PIPE_NAME="\\.\pipe\crashpad_27952_WYYYEXHBNKQDWXHV"
ENV COMMONPROGRAMFILES="C:\Program Files\Common Files"
ENV COMMONPROGRAMFILES(X86)="C:\Program Files (x86)\Common Files"
ENV COMMONPROGRAMW6432="C:\Program Files\Common Files"
ENV COMPUTERNAME="DESKTOP-C04SPAD"
ENV COMSPEC="C:\Windows\system32\cmd.exe"
ENV DRIVERDATA="C:\Windows\System32\Drivers\DriverData"
ENV FPS_BROWSER_APP_PROFILE_STRING="Internet Explorer"
ENV FPS_BROWSER_USER_PROFILE_STRING="Default"
ENV HOMEDRIVE="C:"
ENV HOMEPATH="\Users\Sreyas P Pradeep"
ENV LOCALAPPDATA="C:\Users\Sreyas P Pradeep\AppData\Local"
ENV LOGONSERVER="\\DESKTOP-C04SPAD"
ENV MONGOSH="C:\MongoDB\mongosh-2.3.0-win32-x64\bin"
ENV NUMBER_OF_PROCESSORS="12"
ENV ONEDRIVE="C:\Users\Sreyas P Pradeep\OneDrive"
ENV ONEDRIVECONSUMER="C:\Users\Sreyas P Pradeep\OneDrive"
ENV ORIGINAL_XDG_CURRENT_DESKTOP="undefined"
ENV OS="Windows_NT"
ENV PATH="C:\app\Sreyas\product\21c\dbhomeXE\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\dotnet\;C:\Program Files\dotnet\;C:\MinGW\bin;C:\Program Files\Java\jdk-21\bin;C:\Program Files\MySQL\MySQL Server 8.0\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Sreyas P Pradeep\AppData\Local\Programs\Python\Python312;C:\Users\Sreyas P Pradeep\AppData\Local\Programs\Python\Python312\Scripts;C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR;C:\metasploit-framework\bin\;C:\Users\Sreyas P Pradeep\AppData\Local\flutter\bin;;C:\Program Files\WireGuard\;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\Sreyas P Pradeep\.cargo\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\Sreyas P Pradeep\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\Sreyas P Pradeep\AppData\Local\Programs\Python\Python311\;C:\Users\Sreyas P Pradeep\AppData\Local\Programs\Python\Launcher\;C:\Users\Sreyas P Pradeep\AppData\Local\Microsoft\WindowsApps;C:\Users\Sreyas P Pradeep\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Sreyas P Pradeep\AppData\Roaming\npm;C:\Users\Sreyas P Pradeep\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Nmap;C:\Users\Sreyas P Pradeep\AppData\Local\flutter\bin;C:\Users\Sreyas P Pradeep\AppData\Local\Programs\cursor\resources\app\bin;c:\Users\Sreyas P Pradeep\.vscode\extensions\ms-python.debugpy-2025.4.1-win32-x64\bundled\scripts\noConfigScripts;c:\Users\Sreyas P Pradeep\AppData\Roaming\Code\User\globalStorage\github.copilot-chat\debugCommand"
ENV PATHEXT=".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL"
ENV PROCESSOR_ARCHITECTURE="AMD64"
ENV PROCESSOR_IDENTIFIER="AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD"
ENV PROCESSOR_LEVEL="23"
ENV PROCESSOR_REVISION="6001"
ENV PROGRAMDATA="C:\ProgramData"
ENV PROGRAMFILES="C:\Program Files"
ENV PROGRAMFILES(X86)="C:\Program Files (x86)"
ENV PROGRAMW6432="C:\Program Files"
ENV PSMODULEPATH="C:\Users\Sreyas P Pradeep\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules"
ENV PT8HOME="C:\Program Files\Cisco Packet Tracer 8.2.2"
ENV PUBLIC="C:\Users\Public"
ENV SESSIONNAME="Console"
ENV SSLKEYLOGFILE="C:\Users\Sreyas P Pradeep\SSLKeys\sslkeylog.txt"
ENV SYSTEMDRIVE="C:"
ENV SYSTEMROOT="C:\Windows"
ENV TEMP="C:\Users\SREYAS~1\AppData\Local\Temp"
ENV TMP="C:\Users\SREYAS~1\AppData\Local\Temp"
ENV USERDOMAIN="DESKTOP-C04SPAD"
ENV USERDOMAIN_ROAMINGPROFILE="DESKTOP-C04SPAD"
ENV USERNAME="Sreyas P Pradeep"
ENV USERPROFILE="C:\Users\Sreyas P Pradeep"
ENV VBOX_MSI_INSTALL_PATH="C:\Program Files\Oracle\VirtualBox"
ENV WINDIR="C:\Windows"
ENV TERM_PROGRAM="vscode"
ENV TERM_PROGRAM_VERSION="1.98.1"
ENV LANG="en_US.UTF-8"
ENV COLORTERM="truecolor"
ENV GIT_ASKPASS="c:\Users\Sreyas P Pradeep\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh"
ENV VSCODE_GIT_ASKPASS_NODE="C:\Users\Sreyas P Pradeep\AppData\Local\Programs\Microsoft VS Code\Code.exe"
ENV VSCODE_GIT_ASKPASS_EXTRA_ARGS=""
ENV VSCODE_GIT_ASKPASS_MAIN="c:\Users\Sreyas P Pradeep\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js"
ENV VSCODE_GIT_IPC_HANDLE="\\.\pipe\vscode-git-19ca89e0f0-sock"
ENV PYDEVD_DISABLE_FILE_VALIDATION="1"
ENV VSCODE_DEBUGPY_ADAPTER_ENDPOINTS="c:\Users\Sreyas P Pradeep\.vscode\extensions\ms-python.debugpy-2025.4.1-win32-x64\.noConfigDebugAdapterEndpoints\endpoint-7292c10b1d0f66bd.txt"
ENV BUNDLED_DEBUGPY_PATH="c:\Users\Sreyas P Pradeep\.vscode\extensions\ms-python.debugpy-2025.4.1-win32-x64\bundled\libs\debugpy"
ENV VSCODE_INJECTION="1"
ENV VSCODE_NONCE="8ee008f2-9f1f-4569-8dea-f5d369c63d7a"
ENV VSCODE_STABLE="1"

CMD ["cmd", "/c", "ping", "-t", "localhost", ">", "NUL"]